### ISSUE TITLE
fee negative value

### ISSUE THREAD

**Issue by roccomuso** [vacuumlabs/adalite#665] opened 2020-07-30 22:18 UTC
Am i wrong saying this could return a negative value?

https://github.com/vacuumlabs/adalite/blob/89dffe76bb5b5f90c73ae0ed134527099c9d5534/app/frontend/wallet/shelley/shelley-transaction-planner.ts#L161

**Comment by PeterBenc** [comment] 2020-07-31 13:29
Thanks @roccomuso, this actually was a bug. I've already pushed a fix to the `develop-shelley` branch. You were right, the fee would be negative in this case. Thanks again. 

Closing this since the issue is resolved.

**Closed by PeterBenc** 2020-07-31 13:29 UTC

**Comment by roccomuso** [comment] 2020-07-31 15:44
That was fast ;) great
