### ISSUE TITLE
Refactor debugLog

### ISSUE THREAD

**Issue by jmuravsky** [vacuumlabs/adalite#161] opened 2018-07-30 13:44 UTC
Currently debugLog needs to be dirty patched to work with tests, because config is loaded from HTML body attribute, which is not present in test environment. Whether just debugLog or whole config handling should be refactored needs to be analysed and discussed.

**Comment by refi93** [comment] 2018-08-01 08:39
It also seems to be quite repetitive that before throwing errors, debugLog is being called each time. It would be nice to think about a way to remove this repetitiveness.

**Comment by PeterBenc** [comment] 2020-09-07 16:07
Closing this since the issue is resolved in PR #722. The PR removed all unnecessary debug logs, except those that are in byron files since they will be removed later.

**Closed by PeterBenc** 2020-09-07 16:07 UTC
Labels: low priority
