### ISSUE TITLE
Unable to convert Non-staking balance to stakable balance

### ISSUE THREAD

**Issue by Power2theEdge** [vacuumlabs/adalite#680] opened 2020-08-06 00:31 UTC
Using Adalite in an effort to stake from Ledger Nano S. Successfully delegated my stakable balance, however the majority of the balance (> 100) is categorized as "non-staking". When I click the "convert to stakable link" I receive an error message that reads "Output must be greater than 1 ADA"

**Comment by MichalPetro** [comment] 2020-08-06 08:24
Hi, there is some bug on the convert to staking function. We dont know what is the issue yet because it is happening only occasionally. You can override this by sending all your ADA to one of your Shelley addresses listen in My Addresses tab on the Send screen.

**Comment by PeterBenc** [comment] 2020-08-06 13:57
The problem occurred for users who had utxos with a really small value. (value < fee required to include this input in tx). 
Closing this since the issue is already resolved.

**Closed by PeterBenc** 2020-08-06 13:57 UTC

**Comment by Power2theEdge** [comment] 2020-08-07 00:11
Thank you guys. Michal you are spot on. I used your override option to transfer a small amount to Shelley address and it worked like a charm. Also tried the convert to staking function and it worked, so either it remains an intermittent issue or the staking conversion issue has been resolved. Thanks again.

**Comment by MichalPetro** [comment] 2020-08-07 12:38
yeah this has been fixed, thanks for the patience.
